// src/screens/SignUpStyle.ts
import { Dimensions, StyleSheet } from 'react-native';

const { height, width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: width,
    height: height,
  },
  formContainer: {
    width: width * 0.9,
    padding: 24,
    backgroundColor: 'rgba(17, 24, 39, 0.9)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(75, 85, 99, 0.3)',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  title: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: 'bold',
    marginTop: 16,
    textAlign: 'center',
  },
  subtitle: {
    color: '#9ca3af',
    fontSize: 14,
    marginTop: 8,
    marginBottom: 20,
    textAlign: 'center',
  },
  errorText: {
    color: '#ef4444',
    fontSize: 14,
    marginTop: 12,
    marginBottom: 8,
    textAlign: 'center',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(31, 41, 55, 0.8)',
    borderRadius: 12,
    marginBottom: 16,
    paddingHorizontal: 16,
    width: '100%',
    height: 50,
  },
  input: {
    flex: 1,
    color: '#ffffff',
    fontSize: 16,
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(27, 28, 37, 0.3)',
    borderRadius: 10,
    marginBottom: 15,
    paddingHorizontal: 10,
    width: '100%',
  },
  passwordInput: {
    flex: 1,
    padding: 15,
    color: '#fff',
  },
  signUpButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 14,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
    marginBottom: 16,
  },
  googleButton: {
    flexDirection: 'row',
    backgroundColor: '#1f2937',
    paddingVertical: 14,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(75, 85, 99, 0.5)',
  },
  googleIcon: {
    width: 20,
    height: 20,
    marginRight: 10,
  },
  buttonText: {
    color: '#ffffff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  buttonText2: {
    color: '#ffffff',
    fontWeight: '500',
    fontSize: 16,
  },
  footerContainer: {
    flexDirection: 'row',
    marginTop: 8,
    alignItems: 'center',
  },
  footerText: {
    color: '#9ca3af',
    fontSize: 14,
  },
  signInText: {
    color: '#3B82F6',
    fontWeight: 'bold',
    fontSize: 14,
  },
  eyeIcon: {
    position: 'absolute',
    right: width * 0.05,
    top: height * 0.03,
  },
  eyeIcon2: {
    position: 'absolute',
    right: width * 0.05,
    top: height * 0.03,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#1f2937',
    padding: width * 0.07,
    borderRadius: 12,
    width: '85%',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: height * 0.01,
  },
  modalSubtitle: {
    color: '#aaa',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: height * 0.02,
  },
  codeFieldRoot: {
    marginTop: height * 0.01,
    marginBottom: height * 0.02,
    justifyContent: 'center',
  },
  cell: {
    width: width * 0.11,
    height: width * 0.11,
    lineHeight: width * 0.11,
    fontSize: 20,
    borderWidth: 1,
    borderColor: '#00FF99',
    borderRadius: 10,
    textAlign: 'center',
    marginHorizontal: 4,
    backgroundColor: '#0f172a',
    color: '#fff',
  },
  cellText: {
    color: '#fff',
    fontSize: 20,
    textAlign: 'center',
  },
  cellFocused: {
    borderColor: '#fff',
  },
  modalButtons: {
    marginTop: height * 0.015,
    width: '100%',
    alignItems: 'center',
  },
  verifyButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: height * 0.015,
    paddingHorizontal: width * 0.1,
    borderRadius: 8,
    marginBottom: height * 0.015,
  },
  verifyText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  CancelButton: {
    marginTop: 5,
  },
  cancelText: {
    color: '#aaa',
    fontSize: 14,
  },
});

export default styles;
